appConfig.js
src/app/actions/SearchActions.js
src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/SearchForm/SearchForm.jsx
src/app/components/SearchResults/ResultsList.jsx
src/app/components/SearchResults/SearchResults.jsx
src/app/components/WorkDetail/WorkDetail.jsx
src/app/routes/routes.jsx
src/app/stores/Reducers.js
src/server/ApiRoutes/ApiRoutes.js
src/server/ApiRoutes/Search.js
test/fixtures/work-detail.json
test/unit/SearchForm.test.js
test/unit/WorkDetail.test.js

Adds new actions and client-side logic to fetch individual records from Elasticsearch by UUID and display a work's details.
Adds an onClick action to each search result's title link to fetch and display more details for that particular work and its editions.

Add WorkDetail Page

---

.eslintrc
appConfig.js
src/app/actions/SearchActions.js
src/app/components/Application/Application.jsx
src/app/components/Breadcrumbs/Breadcrumbs.jsx
src/app/components/Error/NotFound404.jsx
src/app/components/List/EBookList.jsx
src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/SearchForm/SearchForm.jsx
src/app/components/SearchResults/ResultsList.jsx
src/app/components/SearchResults/ResultsListItem.jsx
src/app/components/SearchResults/ResultsMetadata.jsx
src/app/components/SearchResults/ResultsRow.jsx
src/app/components/SearchResults/SearchResults.jsx
src/app/components/WorkDetail/DefinitionList.jsx
src/app/components/WorkDetail/WorkDetail.jsx
src/app/constants/fields.js
src/app/search/query.js
src/app/stores/configureStore.js
test/fixtures/results-list-full.json
test/fixtures/results-list.json
test/fixtures/work-detail.json
test/unit/DefinitionList.test.js
test/unit/Query.test.js
test/unit/ResultsList.test.js
test/unit/ResultsRow.test.js
test/unit/SearchContainer.test.js
webpack.config.js

Updated api version, changed search parameters, updated components for ResultList, WorkDetail and EBooks according to new api, all merged with latest changes from breadcrumb.
Also cleaned eslint errors, connected to redux devtools and update webpack to get source maps.

SFR-347 Being able to search v2 indexed data.

---

package-lock.json
package.json
server.js
src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/SearchForm/SearchForm.jsx
src/app/components/SearchResults/ResultsListItem.jsx
src/app/components/WorkDetail/DefinitionList.jsx
src/app/components/WorkDetail/WorkDetail.jsx
src/app/constants/fields.js
test/unit/DefinitionList.test.js

Changed searches API calls to work based upon their components, no need to call the api before and pages work by themselves (no need of server side) and in sync with the store.
Added search by viaf and lcnaf, adding a parameter to the search to show name of author in search box.
Added details about authors on work page and authors in search results.
Simplified some components.
Decode html entities in some values to avoid &amp in texts

Sfr 351 search by viaf

---

src/app/components/Form/TextInput.jsx
src/app/components/SearchForm/SearchForm.jsx
src/client/styles/components/Search.scss
test/unit/SearchForm.test.js

* Added a fix to the background color which overlapped the magnifying glass icon in the button at smaller widths
* Added a breakpoint for the input/button combo for smaller screens according to the [UX documentation](https://docs.google.com/presentation/d/1GuhHGdXW6LmJtLiQSJw4UFMUwE5bpuObgpfx1E5Kjdg/edit#slide=id.g4cf15899e7_0_86) (page 26)
* Removed placeholder text as per [UX documentation](https://docs.google.com/presentation/d/1GuhHGdXW6LmJtLiQSJw4UFMUwE5bpuObgpfx1E5Kjdg/edit#slide=id.g4cf15899e7_0_86) (page 26)

Add small improvements for search form input/button combo

---

src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/SearchForm/SearchForm.jsx
test/unit/ResultsList.test.js
test/unit/SearchForm.test.js

* Changes to `div` wrappers for form elements with accompanying props (role, aria-label).
* Adds labels as per UX documentation.
* Adds tests and adjust error in ResultsList test.

Addresses SFR-328

---

src/app/components/SearchResults/SearchHeader.jsx
src/client/styles/components/SearchHeader.scss

Rearrange order of elements for labels accessibility and fixed design

SFR-430 Bad VoiceOver reading order for results headings

---

src/app/components/List/AuthorsList.jsx
src/app/components/WorkDetail/WorkHeader.jsx

As we show only one author in lists and header of work item, and only the first one with the role 'author', the filter was doing it wrong.

SFR-408 author name not displaying

---

src/app/components/Form/Select.jsx
src/app/components/SearchResults/ResultsMetadata.jsx
src/app/components/SearchResults/SearchFooter.jsx
src/app/components/SearchResults/SearchHeader.jsx
src/app/components/SearchResults/SearchNavigation.jsx
src/app/components/SearchResults/SearchResults.jsx
src/app/components/WorkDetail/WorkDetail.jsx
src/client/styles/components/EBookList.scss
src/client/styles/components/EditionsList.scss
src/client/styles/components/Search.scss
src/client/styles/components/SearchFooter.scss
src/client/styles/components/SearchHeader.scss
src/client/styles/main.scss

After test review from Chris, this commit solve the differences found:
Added Search Footer.
Fixed some margins
First, next, previous links shouldn't be underlined
Page shown 1 of total
Format numbers
Added line down view all editions
Fix font in usa-table
Added functionality in Select to accept value and label.
SearchFooter is very similar to SearchHeader but I think it's better to keep them separated for better maintenance

SFR-391 Implement design / component.

---

src/app/components/SearchForm/SearchForm.jsx
src/app/stores/InitialState.js

Better to reset the search fields before making a new search

SFR-438 wrong text indicating number of items showing

---

src/app/components/SearchResults/ResultsListItem.jsx
src/app/components/WorkDetail/WorkHeader.jsx

Check if there is an agent with role=author before displaying author list in header of workitem and in search results

SFR-408 author name not displaying.

---

package-lock.json
package.json
src/app/stores/configureStore.js

Synchronize Store with session storage.
Also update library for audit vulnerabilities

SFR-446 Use session storage. Also update library for audit

---

src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/WorkDetail/WorkDetail.jsx

Removed "search results" and "back to search results" link when there is no search result in the store

SFR-402 Change hierarchy in breadcrumb

---

src/app/actions/SearchActions.js
src/app/components/Application/Loading.jsx
src/app/components/List/EBookList.jsx
src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/SearchForm/SearchForm.jsx
src/app/components/SearchResults/Filters.jsx
src/app/components/SearchResults/SearchNavigation.jsx
src/app/components/SearchResults/SearchResults.jsx
src/app/search/query.js
src/app/stores/InitialState.js
src/app/stores/Reducers.js
src/client/styles/components/Filters.scss
src/client/styles/components/Loading.scss
src/client/styles/main.scss
test/fixtures/results-list-full.json
test/unit/Filters.test.js

Filters component, prepare query for filters
Added action for error, and displaying error in loading modal.
Make sure the booklist has unique values
Solved a warning in SearchForm
Unique Id for search header and footer
Added Filters unit test

SFR-397 Implement filters in front end.

---

src/app/components/WorkDetail/DefinitionList.jsx

SFR-462 Subjects sorted alphabetically on Item Details page

---

src/app/components/List/EBookList.jsx

First read online, then download

SFR-411 Order the links

---

src/app/components/Form/Select.jsx
src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/SearchResults/SearchNavigation.jsx
src/app/constants/sorts.js
src/app/search/query.js
src/app/stores/InitialState.js
test/unit/SearchNavigation.test.js

Added tests for all links and selects of searchnavigation
sortBy Map and list of numbersByPage in separate file.
Added data-test for easier testing

Sfr 81 sort by title

---

src/app/components/Form/Select.jsx
src/app/components/SearchForm/SearchForm.jsx
src/app/components/SearchResults/FilterYears.jsx
src/app/components/SearchResults/Filters.jsx
src/app/constants/labels.js
src/app/search/query.js
src/server/ApiRoutes/Search.js
test/unit/FilterYears.test.js
test/unit/Filters.test.js

Added Filter for years.
Also some improvements to make search work on no-js

Sfr 481 date filter

---

server.js
src/app/components/Application/Application.jsx
src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/WorkDetail/WorkDetail.jsx
src/app/constants/labels.js
src/app/util/Util.js

Also solved bug when going back to home that didn't remove results.
And improvement on isEmpty util that wasn't working 100%

SFR-495 Titles need to follow UX documentation

---

src/app/components/List/EditionsList.jsx
src/app/components/WorkDetail/WorkDetail.jsx
src/client/App.jsx

SFR-502 View all shortcut only works visually.

---

src/app/components/SearchResults/SearchNavigation.jsx
src/app/constants/sorts.js
test/unit/SearchNavigation.test.js

SFR-528 Implement date sorting in front-end app

SFR-532 Implement author sorting in front-end app

---

src/app/components/SearchResults/Filters.jsx
test/unit/Filters.test.js

Added a filter to show the filter fields when there is searchQuery about them but no results

SFR-538 An empty result set leaves with with no options for refining

---

src/app/components/AdvancedSearch/AdvancedSearch.jsx
src/app/components/SearchResults/FilterYears.jsx
src/app/components/SearchResults/Filters.jsx

Changed to onBlur for Years Filter and refactored to keep the error state in the upper component, AdvancedSearch of Filters

Years Filter onBlur

---

src/app/components/AdvancedSearch/AdvancedSearch.jsx
src/app/components/Application/Loading.jsx
src/app/components/List/EBookList.jsx
src/app/components/SearchContainer/SearchContainer.jsx

Bugfixes:
- Filter out items with no links
- Don't re-do search when results are available
- Don't call redux ERROR action when there is no error

SFR-578: Item with no links causes error

---

src/app/components/SearchContainer/SearchContainer.jsx
src/app/components/SearchResults/FilterYears.jsx
src/app/components/SearchResults/Filters.jsx
test/helpers/routing.js
test/unit/Filters.test.js

- Filter Refactor to isolate functions
- Error validation for sidebar filter years

SFR-581 Bugfixes

---

src/app/components/List/EBookList.jsx

SFR-582 Clean Up React Warnings

---

src/app/libraries/react-dropdown-aria.jsx

Missed this the first time around

Made another dropdown key unique

---

.eslintrc
appConfig.js
featureFlagConfig.js
src/app/actions/SearchActions.js
src/app/components/SearchForm/SearchForm.jsx
src/app/components/SearchForm/TotalWorks.jsx
src/app/stores/InitialState.js
src/app/stores/Reducers.js
src/app/util/Util.js
src/client/App.jsx

SFR-381 Added Work count controlled by feature flag

---

src/app/components/Breadcrumbs/Breadcrumbs.jsx

SFR-616 Clean-up

---

appConfig.js
package-lock.json
package.json
src/app/components/Application/Application.jsx
src/app/components/Feedback/Feedback.jsx
src/client/styles/components/Feedback.scss
src/client/styles/main.scss
test/unit/Feedback.test.js
webpack.config.babel.js

This adds a feedback button for user bug reports/responses to the ResearchNow app. The base for this form was borrowed from Shared Collections Catalog and modified with new styles, a new question and a new integration. It has also been updated to work with our version of React, which is somewhat newer than what is in use on SCC.
This sends the responses to an Airtable spreadsheet, which is easier to work with than a Google Sheet Integration.
This has only a very basic test and I'm not sure if the best thing to do is to add more tests now or have some basic tests in place and build out the test suite in the future.

SFR-442 add feedback form

---

package-lock.json
package.json
src/app/components/SearchResults/SearchResultsPage.jsx
test/unit/SearchResultsPage.test.js

Changes unintended search URLs to redirect to landing page.

SFR-804 invalid Search url routing

---

CHANGELOG.md
package.json

How we keep package and changelog up to date : 
1) Add to changelog as a part of ticket work, but don't change package.json
2) Bump package.json and release at sprint review
This should work for us until we get to a 1.0 release.

SFR-812 changelog

---

package-lock.json
src/app/components/Card/EditionCard.jsx
src/app/components/SearchResults/ResultsList.jsx
src/app/components/WorkDetail/WorkDetail.jsx
test/helpers/routing.js
test/unit/SearchResultsPage.test.js

Changed:  Request Edition button now is an `<a>` tag that calls onClick.  
(Currently this is the easiest way to give it the "link" class).

Changed Request Edition Button to look like a link

---

.github/PULL_REQUEST_TEMPLATE

NO-REF Added PR template

---

package-lock.json
package.json
src/app/components/Card/EditionCard.jsx
src/app/components/License/License.jsx
src/app/routes/routes.jsx
test/unit/EditionCard.test.js
test/unit/ResultsList.test.js

[Jira Ticket](http://jira.nypl.org/browse/SFR-135)
- Added License Explanations page and links to it from the edition card
-  Run SFR and make sure that license links to the "License Explanations" page.  
- Will there always be only one license?  This model breaks if there's more than one license ...

SFR-135 license explanations

---

src/app/components/Feedback/RequestDigital.jsx
src/app/components/SearchResults/ResultsList.jsx
src/app/components/WorkDetail/WorkDetail.jsx
src/client/styles/components/RequestDigitization.scss

[Jira Ticket](http://jira.nypl.org/browse/SFR-89)
- Fixes some bugs that come out of QA: 
-- Modal appears on top of fotoer
-- Request digitization requires checking a radio button
-- Small copy tweak
-  Verify the above

SFR-89 request digitization

---

src/app/components/License/License.jsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-135)
- Addressed some comments that came up in QA: 
- Typos 
- Scrolls to top on page load
-  Typo free license page?

SFR-135 Scrolls to top on page load

---

src/app/components/Feedback/RequestDigital.jsx
src/client/styles/components/RequestDigitization.scss
test/unit/RequestDigital.test.js

[Jira Ticket](http://jira.nypl.org/browse/SFR-89)
- Removed the "I want any edition" option
- The radio buttons are no longer required - submitting an empty form submits the work/edition to Airtable.  
-

SFR-89 Removed Confusing Option

---

CHANGELOG.md
package.json

No Jira Ticket
- Bumps package and changelog for release
-

NO-REF releasing 8.2

---

src/app/components/Application/Loading.jsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-827)
- Passes a null error message so that it doesn't persist
-  your browser tools has a feature to block requests ( https://stackoverflow.com/questions/27863094/how-to-block-a-url-in-chromes-developer-tools-network-monitor )

Sfr 827 persistent error message

---

src/app/components/Application/Loading.jsx
src/app/components/Card/EditionCard.jsx
src/app/components/SearchResults/ResultsList.jsx
src/app/components/WorkDetail/WorkDetail.jsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-827)
- Changed the location of the error message replace so it's null when a request happens.
-

SFR-827 Changed location of error state set

---

package-lock.json
src/app/components/About/About.jsx
src/app/routes/routes.jsx

- Added the about page which can be accessed by appending `/About`
-

SFR-863 added about page

---

src/app/components/Card/EditionCard.jsx
src/app/components/LandingPage/LandingPage.jsx
src/client/styles/main.scss

- changed unavailable copy
- overrode Header with Search styles
- Changed "browse by subject" copy
-

SFR-865 more pre-beta fixes

---

src/app/components/Application/Application.jsx
src/app/components/SearchResults/SearchResultsPage.jsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-875)
- Puts the mobile apology message on all the pages. 
-

SFR-875 put apology message on every page

---

src/app/components/AdvancedSearch/AdvancedSearch.jsx
src/app/components/Feedback/RequestDigital.jsx
src/app/components/LandingPage/LandingPage.jsx
src/app/components/SearchForm/WithSearch.jsx
src/app/stores/InitialState.js

[Jira Ticket](http://jira.nypl.org/browse/SFR-843)
- Prepopulates advanced search fields based on visible queries (This is more clear than populating on non-visible queries in unlikely case of conflict) 
- Clears non-visible queries when moving to adv search.
-

SFR-843 adv search persistent state

---

src/app/components/SearchResults/SearchResultsPage.jsx
src/app/search/query.js
src/app/stores/InitialState.js
subjectListConfig.js

[Jira Ticket](http://jira.nypl.org/browse/SFR-843)
- Bugfix:  Old changes broke Browse By linking (and direct linking), this fixes them.  
-

SFR-843 Fixed link JSON parsing

---

src/app/components/Viewer/EBookViewer.jsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-803)
- Removed noScroll from iframes
-

SFR-803 enabled scrolling on iframes

---

CHANGELOG.md
package.json

- Prepares for 0.8.3 release
-

NO-REF bump package and changelog

---

CHANGELOG.md
package-lock.json
package.json
server.js
src/app/components/Application/Application.jsx
src/app/components/SearchResults/SearchResultsPage.jsx
src/app/constants/labels.js

[Jira Ticket](http://jira.nypl.org/browse/SFR-788)
- Changed "Search results" capitalization
- Fixed document title on the various pages
-

SFR-788 copy changes

---

CHANGELOG.md
README.md
package-lock.json
package.json

[Related Jira ticket](https://jira.nypl.org/browse/RENO-1153)
**This PR does the following:**
- Updates dgx-react-footer to v0.5.5

RENO-1153: Update dgx-react-footer to v.0.5.5

---

.ebextensions/00_environment.config
.ebextensions/ebnode.py

A new/udpated npm package is causing a conflict with the AWS EBS environment. It is outputting unexpected non UTF-8 characters during the install process and this causes deployments to fail. This fix, which is supposedly the official recommendation from AWS is to pipe the output of the NPM install process to /dev/null. This removes the ability to easily review installation logs for troubleshooting, but does allow for deployments. Review should be made in the future to see if this can be removed.
NO JIRA TICKET
- Patches AWS ElasticBeanstalk deployment process
-  No testing required
- Review config files for sanity

HOTFIX AWS Elastic Beanstalk Environment Fix

---

src/app/actions/SearchActions.js

Proper import from constants/fields

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/client/styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/RENO-1275)
- Updates dgx-react-footer to v0.5.6
- Resets the box-sizing for the footer element

RENO-1275: Update dgx-react-footer to v0.5.6

---

package-lock.json
src/app/components/Viewer/EBookViewer.jsx

- the Reader page is using `state` to populate breadcrumbs, and this doesn't work when you navigate to it directly.  This PR makes the breadcrumb default to go home if a user navigates directly to the reader. 
-  Pasting a reader link into browser loads the reader and book

NO-REF Allow direct links to reader page

---

CHANGELOG.md
README.md
package.json
src/app/components/Detail/WorkDetailDefinitionList.jsx
src/app/components/SearchForm/WithSearch.jsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-935)
- Fixes a bug where changing the field with a prepopulated author would show the author viaf
- Fixes another bug where the app would crash if you clicked a subject and tried to change the search term
-  play around with the search bar and see if issues persist

SFR-935 searchbar clears when field changes

---

package-lock.json
package.json
src/app/components/About/About.jsx
src/app/components/Card/EditionCard.jsx
src/app/components/Detail/EditionDetail.jsx
src/app/components/Detail/WorkDetailDefinitionList.jsx
src/app/components/LandingPage/LandingPage.jsx
src/app/components/License/License.jsx
src/app/components/SearchForm/SearchHeader.jsx
src/app/components/SearchResults/Filters.jsx
src/app/components/SearchResults/SearchResultsPage.jsx
src/client/styles/components/DefinitionList.scss
src/client/styles/components/Filters.scss
src/client/styles/components/Search.scss
src/client/styles/main.scss
test/unit/Filters.test.js
webpack.config.babel.js

- upgrades SFR to use Design System 0.4.0
- New overrides to beautify
-  Check for regressions in front end app

SFR-937 Upgrade DS to 0.4.1 

---

CHANGELOG.md
src/app/components/Application/Application.jsx

- Removes mobile apology message
-

SFR-941 remove mobile apology

---

package-lock.json
src/app/components/About/About.jsx

NO-JIRA
- fixes some copy on the about page
-

NOREF small copy fix

---

.github/workflows/ci.yml
package.json

Moving typescript deps out of devdependencies

---

.github/workflows/build-branch-qa.yaml

This makes two updates to the QA environment generation process:
1) The IPs provided are now the "Public" IP addresses and can be accessed outside of the VPN
2) The action now produces a new comment for each run, to ensure that changed IP addresses are provided to reviewers/testers
- Tested on the back-end repository

HOTFIX Update Temp QA Environment URL

---

src/components/Layout/Layout.tsx
styles/main.scss

- A previous PR broke the CSS of the feedback button.  This adds it back.  
-

Added visual feedback button

---

src/__tests__/Search.test.tsx
src/components/Search/Search.tsx
src/types/SearchQuery.ts

- Adds commas in the item count 
-

Added commas in item count

---

src/components/SearchForm/SearchForm.tsx
src/components/SearchHeader/SearchHeader.scss
src/components/SearchHeader/SearchHeader.tsx

- Moved HelperErrorText out of searchbar
- Changed styling on headerWithSearch so that the searchbar doesn't move around
-

SFR-1072 Moved helperErrorText out of searchbar

---

src/components/Work/Work.test.tsx
src/components/Work/Work.tsx
src/lib/api/SearchApi.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1112)
- Changes work page so that show_all is unchecked by default
-

Work page defaults to show everything

---

src/__tests__/Search.test.tsx
src/components/Search/Search.tsx

displays item count when it is less than perPage

---

src/__tests__/fixtures/edition-detail.json
src/components/EditionDetail/Edition.test.tsx
src/components/EditionDetail/Edition.tsx
src/components/EditionDetailDefinitionList/EditionDetailDefinitionList.test.tsx
src/components/ReaderLayout/ReaderLayout.tsx
src/types/EditionQuery.ts

Truncates title in breadcrumb

---

src/components/EditionDetail/Edition.test.tsx
src/components/EditionDetail/Edition.tsx
src/lib/api/SearchApi.ts

Edition page defaults to show everythign

---

package-lock.json

Merge back prod

---

CHANGELOG.md
src/components/Layout/Layout.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1137)
- Fixes footer hover color
-

SFR-1137 fixed footer hover link color

---

.github/workflows/build-branch.yaml
.github/workflows/destroy-branch.yaml

- Makes it so that preview environments build on PR to "production" as well as "qa" 
-

Builds branches on PRs to QA and Production

---

CHANGELOG.md
src/components/Layout/Layout.tsx

Reverts NYPL/sfr-bookfinder-front-end#239

Revert "SFR-1137 fixed footer hover link color"

---

CHANGELOG.md
package.json
src/components/Layout/Layout.tsx

Footer hover fix

---

CHANGELOG.md
src/components/Layout/Layout.tsx
src/constants/labels.ts
src/pages/_app.tsx

SFR-1135 header favicon console error

---

CHANGELOG.md
src/components/AdvancedSearch/AdvancedSearch.tsx
src/lib/api/SearchApi.ts

- Removes languages from advanced search if no response is received
-  Make sure Advanced Search is still working

NO-REF Removes languages from advanced search if not received

---

CHANGELOG.md
src/components/AdvancedSearch/AdvancedSearch.tsx
src/lib/api/SearchApi.ts
task-definition.json

- Merges the languages hotfix to production
-

HOTFIX-Handles languages api error

---

.env.sample
README.md

[Jira Ticket](http://jira.nypl.org/browse/SFR-1167)
- Updates readme so it reflects the current app state
-  read through the readme, maybe try installing and running the app, and see if it all makes sense?  
- Make sure the info is actually accurate, especially about the features

SFR-1167 Updated readme

---

task-definition.json

As part of handling production traffic loads on DRB the elasticsearch client changed, and the new endpoint needs to be provided to the test environments here.
-  Validate that the test environment can query the API

NOREF Update ES endpoint

---

CHANGELOG.md
package-lock.json
package.json
src/__tests__/AdvancedSearch.test.tsx
src/__tests__/Search.test.tsx
src/__tests__/componentHelpers/SearchForm.tsx
src/__tests__/fixtures/results-list.json
src/components/AdvancedSearch/AdvancedSearch.tsx
src/components/EditionDetail/Edition.test.tsx
src/components/EditionDetail/Edition.tsx
src/components/Layout/Layout.tsx
src/components/Search/Search.tsx
src/components/SearchForm/SearchForm.tsx
src/components/SearchHeader/SearchHeader.tsx
src/components/Work/Work.test.tsx
src/constants/fields.ts
src/constants/labels.ts
src/lib/api/SearchApi.ts
src/pages/advanced-search/index.tsx
src/pages/search/index.tsx
src/types/DataModel.ts
src/types/SearchQuery.ts
src/util/EditionCardUtils.tsx
src/util/__tests__/apiConversion.test.ts
src/util/apiConversion.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-992)
- Re-enables viaf search
-  Search by viaf and make sure it works

SFR-992 Re-enabled viaf search

---

README.md
src/lib/api/SearchApi.ts

preparing for 0.10.2 release

---

CHANGELOG.md
README.md
package.json
src/__tests__/componentHelpers/SearchForm.tsx
src/__tests__/index.test.tsx
src/components/About/About.tsx
src/components/AdvancedSearch/AdvancedSearch.tsx
src/components/EditionDetail/Edition.tsx
src/components/Landing/Landing.tsx
src/components/Layout/Layout.tsx
src/components/License/License.tsx
src/components/License/__snapshots__/License.test.tsx.snap
src/components/Search/Search.tsx
src/pages/404.tsx
src/pages/_document.tsx
src/pages/_error.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1190)
- Added document.tsx to add props to html tag and moved <main> to Layout component
-

A11Y fixes

---

CHANGELOG.md
styles/components/Landing.scss
styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/SFR-1214)
- Changes link color when on grey background
-  Make sure that text contrast on page is 4.5:1

SFR-1214 link color on gray background has adequate contrast

---

CHANGELOG.md
package.json
src/components/AdvancedSearch/AdvancedSearch.tsx
src/components/Layout/Layout.tsx
src/components/ResultsFilters/ResultsFilters.tsx
src/components/Work/Work.tsx
src/pages/search/index.tsx
styles/components/Search.scss

- Adds sidebar class to main by adding a prop into the `<Layout />` component
- This eliminates the need to define a `<main>` component in each page. 
-

Re-adds missing class to search results

---

CHANGELOG.md
src/__tests__/AdvancedSearch.test.tsx
src/components/AdvancedSearch/AdvancedSearch.tsx
src/components/SearchHeader/SearchHeader.tsx
src/pages/advanced-search/index.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1215)
- Clicking `Advanced Search` should start a new search. 
-  Make sure all the search fields are cleared out on the advanced-search page each time we start a search.

Sfr 1215 clear search terms

---

README.md
package-lock.json
package.json

preparing for 0.10.4 release

---

CHANGELOG.md
src/__tests__/fixtures/EditionCardFixture.ts
src/__tests__/fixtures/edition-detail.json
src/__tests__/fixtures/results-list.json
src/__tests__/fixtures/work-detail.json
src/components/EditionCard/EditionCard.test.tsx
src/components/EditionCard/EditionCard.tsx
src/components/EditionDetail/Edition.tsx
src/components/InstanceCard/InstanceCard.test.tsx
src/components/InstanceCard/InstanceCard.tsx
src/components/ReaderLayout/ReaderLayout.tsx
src/components/Work/Work.tsx
src/constants/auth.ts
src/types/DataModel.ts
src/types/LinkQuery.ts
src/util/EditionCardUtils.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-944)
- Added the missing EDD button to the edition detail page.
- Use the `item.link.flags` tag to determine the media type.  
-

Add EDD button to the edition detail page

---

CHANGELOG.md
src/components/ReaderLayout/ReaderLayout.tsx
src/components/Search/Search.tsx
src/lib/api/SearchApi.ts
src/types/SearchQuery.ts
src/util/__tests__/apiConversion.test.ts
src/util/apiConversion.ts

- Addes "back to digital research books" button 
- Defaults search results to use v2 readerversion when it is not passed to the url
-

Default to ReaderVersion v2

---

src/util/EditionCardUtils.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-944)
- Encode redirect_uri so that it can properly redirect users after logging in
-

Encode redirect_uri

---

.env.sample
CHANGELOG.md
Dockerfile
jest.config.js
jest.setEnv.ts
next.config.js
package-lock.json
package.json
src/components/ReaderLayout/ReaderLayout.tsx
src/components/WebpubViewer/WebpubViewer.tsx
src/components/Work/Work.tsx
src/constants/mediaTypes.ts
src/lib/api/SearchApi.ts
src/types/DataModel.ts
src/types/SearchQuery.ts
src/types/WorkQuery.ts
src/util/EditionCardUtils.tsx
src/util/reader.ts

NO-REF add reader toggle

---

task-definition.json

Added env variable to task definition

---

package.json

Fixing a typo in package json

---

.github/workflows/rspec-integration-tests.yml

run rspec against qa

---

Dockerfile
task-definition.json

changed env variable to release v2reader to qa

---

package-lock.json
package.json

- Upgrade @nypl/web-reader to 0.3.0 which includes 
- Fixed Two scrollbars bug
- Moved floating page button to a sticky footer
- Hide prev/next buttons on the first/last page
-

Upgrade webreader to 0.3.0

---

README.md
package.json

Bump Version number and linting

---

.env.sample
.github/workflows/ci.yml
.npmrc
CHANGELOG.md
README.md
package-lock.json
package.json
src/components/ReaderLayout/ReaderLayout.tsx
src/pages/_app.tsx

-  Uses Webreader V1
- Some CI fixes to help with install and reduce some friction
-

SFR-1430 webreader v1

---

CHANGELOG.md
src/__tests__/fixtures/work-only-catalog-link.json
src/components/Work/Work.test.tsx
src/components/Work/Work.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1358)
- Handles the edge case for when a work only has a catalog link available by not showing Featured Edition section.
-

SFR-1358: Handle edge case for work with catalog link

---

CHANGELOG.md
README.md
package.json

NOREF prepare 0.13.0 release

---

CHANGELOG.md
package-lock.json
src/components/EditionDetail/Edition.test.tsx
src/components/EditionDetail/Edition.tsx
src/components/Work/Work.test.tsx
src/components/Work/Work.tsx
src/pages/edition/[editionId].tsx
src/pages/work/[workId].tsx
src/util/LinkUtils.ts
src/util/__tests__/LinkUtils.test.tsx
styles/main.scss
styles/shared/BackToSearchResults.scss

[Jira Ticket](http://jira.nypl.org/browse/SFR-850)
- Adds back to search results link to works and editions
-

SFR-850: Add back to search results link

---

CHANGELOG.md
package.json

NOREF prepare 0.13.1 release

---

CHANGELOG.md
package-lock.json
package.json
src/components/ReaderLayout/ReaderLayout.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1413)
- 
-

SFR-1413: Upgrade to web reader v3.1.0

---

package.json

NO-REF fixing QA build deploy

---

package-lock.json
package.json
src/components/About/About.test.tsx
src/components/About/__snapshots__/About.test.tsx.snap
src/components/AdvancedSearch/AdvancedSearch.tsx
src/components/InstanceCard/InstanceCard.tsx
src/components/License/License.test.tsx
src/components/License/__snapshots__/License.test.tsx.snap
src/components/Link/Link.tsx
src/components/Search/Search.tsx
src/components/SearchForm/SearchForm.tsx
src/components/SearchHeader/SearchHeader.scss
src/components/SearchHeader/SearchHeader.tsx
src/util/EditionCardUtils.tsx
styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/SFR-1473)
- [SFR-1473](http://jira.nypl.org/browse/SFR-1473), [SFR-1477](http://jira.nypl.org/browse/SFR-1477), [SFR-1483](http://jira.nypl.org/browse/SFR-1483), [SFR-1484](http://jira.nypl.org/browse/SFR-1484), [SFR-1485](http://jira.nypl.org/browse/SFR-1485)
-

SFR-1473: Resolve bugs from DS upgrade

---

CHANGELOG.md
package.json

NOREF prepare 0.14.0 release 

---

CHANGELOG.md
cucumber.js
jest.config.js
package-lock.json
package.json
playwright/features/helloWorld.feature
playwright/support/setup.ts
playwright/tests/helloWorld.spec.ts
tsconfig.json

[Jira Ticket](http://jira.nypl.org/browse/SFR-1504)
- Sets up a very basic Cucumber and Playwright configuration for running end-to-end tests
-  Checkout this branch and run `npm run cucumber` and a simple Playwright test should pass

SFR-1504: Add cucumber and playwright

---

CHANGELOG.md
package-lock.json
package.json

NOREF prepare 0.14.1 release

---

.gitignore
CHANGELOG.md
cucumber.js
playwright/NOTES.txt
playwright/features/authorSearch.feature
playwright/features/homePageElements.feature
playwright/features/keywordSearch.feature
playwright/tests/authorSearch.spec.ts
playwright/tests/homePageElements.spec.ts
playwright/tests/keywordSearch.spec.ts

Author search playwright

---

CHANGELOG.md
src/__tests__/AdvancedSearch.test.tsx
src/__tests__/Search.test.tsx
src/components/AdvancedSearch/AdvancedSearch.tsx
src/components/ResultsFilters/ResultsFilters.tsx
src/constants/filters.ts
src/util/SearchQueryUtils.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1544)
- Add gov doc filter to search results and advanced search pages
-

SFR-1544: Add gov doc filter

---

CHANGELOG.md
playwright/NOTES.txt
playwright/features/ReadOnlineTargets.feature
playwright/support/setup.ts
playwright/tests/readOnlineTargets.spec.ts

Readonline playwright

---

CHANGELOG.md
playwright/features/itemDetailPageElements.feature
playwright/tests/itemDetailPageElements.spec.ts

adding playwright tests for item detail page

---

CHANGELOG.md
package-lock.json
package.json

NOREF prepare 0.15.1 release

---

src/components/Layout/Layout.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1560)
- Add urlType prop to Header to use absolute links
-

SFR-1560: Add urlType to Header

---

CHANGELOG.md
package-lock.json
package.json

NOREF prepare 0.16.0 release

---

CHANGELOG.md
package-lock.json
package.json

NOREF prepare 0.16.1 release

---

CHANGELOG.md
config/appConfig.ts
src/__tests__/fixtures/CollectionFixture.ts
src/components/CollectionCard/CollectionCard.test.tsx
src/components/CollectionCard/CollectionCard.tsx
src/components/CollectionList/CollectionList.test.tsx
src/components/CollectionList/CollectionList.tsx
src/components/Landing/Landing.test.tsx
src/components/Landing/Landing.tsx
src/lib/api/CollectionApi.ts
src/pages/index.tsx
src/types/CollectionQuery.ts
src/types/OpdsModel.ts
src/util/CollectionUtils.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1587)
- Adds type definitions for OPDS2 Feed
- Replaces Search Examples with Recently Added Collections on the landing page
- Adds tests for `CollectionList` and `CollectionCard`
-

SFR-1587: Implement collection list

---

CHANGELOG.md
src/components/CollectionList/CollectionList.tsx
src/components/Landing/Landing.tsx
src/components/Layout/Layout.test.tsx
src/components/Layout/Layout.tsx
src/components/SearchForm/SearchForm.tsx
src/components/SearchHeader/SearchHeader.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1561)
- Add primary hero to landing page
- Removes `<main>` from `Layout` since it is included in DS `Template` used on every page
-

SFR-1586: Add primary hero to landing page

---

src/__tests__/fixtures/CollectionFixture.ts
src/components/Collection/Collection.test.tsx

- Address test comments from #388 
- Clean up collection fixture for reusability
-

SFR-1588: Revise tests from collection page branch

---

CHANGELOG.md
src/components/CollectionCard/CollectionCard.tsx
src/components/CollectionList/CollectionList.tsx
src/components/Landing/Landing.tsx
src/constants/collection.ts

[VQA Doc](https://docs.google.com/document/d/1LUMKaBmzIJ58xvRRtP85iBmVkriodnAx3U5zd70eAAc/edit?usp=sharing)
- Fixes issues with mobile view and card text spacing.
-

Fix Collections VQA Issues

---

CHANGELOG.md
src/components/CollectionCard/CollectionCard.test.tsx
src/components/CollectionCard/CollectionCard.tsx
src/components/EditionDetail/Edition.tsx
src/components/SearchForm/SearchForm.tsx
src/components/Work/Work.tsx
src/constants/collection.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1646)
- Updates the collection placeholder image for collection cards on the landing page and Part of Collection in the work/edition detail pages.
- Fixes some minor UI issues with card resizing and spacing.
-

SFR-1646: Update collection image

---

.gitignore
CHANGELOG.md
cucumber.json
playwright/features/homePageElements.feature
playwright/tests/homePageElements.spec.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1675)
- Adds Playwright tests to check the collections section on the homepage
-  Running Playwright tests and all tests pass

SFR-1675: Playwright tests on homepage collections

---

src/components/CollectionCard/CollectionCard.test.tsx
src/components/Landing/Landing.tsx
src/constants/collection.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1663)
- Update hero images based on VQA
- Update collection card placeholder image
-

SFR-1663: Update hero image links

---

CHANGELOG.md
playwright/features/ReadOnlineTargets.feature
playwright/features/advSearch.feature
playwright/features/authorSearch.feature
playwright/features/edd.feature
playwright/features/govDocsFilter.feature
playwright/features/keywordSearch.feature
playwright/features/languageFilter.feature
playwright/features/pub_yearFilter.feature
playwright/features/subjectSearch.feature
playwright/features/titleSearch.feature
playwright/support/mappings.ts
playwright/tests/advSearch.spec.ts
playwright/tests/authorSearch.spec.ts
playwright/tests/click.spec.ts
playwright/tests/edd.spec.ts
playwright/tests/govDocsFilter.spec.ts
playwright/tests/keywordSearch.spec.ts
playwright/tests/languageFilter.spec.ts
playwright/tests/pub_yearFilter.spec.ts
playwright/tests/readOnlineTargets.spec.ts
playwright/tests/subjectSearch.spec.ts
playwright/tests/titleSearch.spec.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1694)
- Created a single function that accepts a locator as a parameter and clicks on it
- Refactored Cucumber/Playwright tests so that all click actions/events use the same function
-  Run Playwright tests and all tests pass

SFR-1694: Refactor click actions in Playwright tests

---

CHANGELOG.md
package-lock.json
package.json

NOREF prepare 0.17.1 release

---

Dockerfile

[Jira Ticket](http://jira.nypl.org/browse/SFR-1690)
-
-

SFR-1690: Add arg definition to Dockerfile

---

src/components/AdvancedSearch/AdvancedSearch.tsx
src/constants/analytics.ts
src/constants/labels.ts
src/pages/_app.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1690)
- Fix issues from BlastX [QA](https://nypl.slack.com/archives/C04UFSSL4SV/p1687191735377659)
-

SFR-1690: Fix adobe analytics issues

---

CHANGELOG.md
package-lock.json
package.json

NOREF prepare 0.17.2 release

---

CHANGELOG.md
playwright/features/eReader-settings.feature
playwright/support/mappings.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1729)
This PR verifies the features (ToC, Settings, Full-Screen, back to DRB button) of eReader for DRB project.

SFR-1729: Verify eReader settings features

---

CHANGELOG.md
package-lock.json
package.json

NOREF prepare 0.17.3 release

---

CHANGELOG.md
src/components/ReaderLayout/ReaderLayout.tsx
src/lib/Analytics.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1739)
- Add id as subsection for "Read Online" CTA analytics tracking
-

SFR-1739: Analytics - add id as subsection

---

CHANGELOG.md
playwright/features/itemDetailPageElements.feature
playwright/support/mappings.ts
playwright/tests/click.spec.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1746)
- verifies the toggle read only button on item details page
- verifies search textfields, dropdown, advance search text field
- added double click function on click.spec.ts file

Sfr 1746/item details page toggle button

---

CHANGELOG.md
playwright/features/advSearch.feature
playwright/support/mappings.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1748)
Verifies the advanced search page headers and footers links.

SFR-1748/verify-header-footer-advSearc

---

CHANGELOG.md
playwright/features/itemDetailPageElements.feature
playwright/support/mappings.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1755)
- fixes automated tests that were failing

SFR-1755/fix_pw_tests

---

CHANGELOG.md
package-lock.json
package.json

NOREF prepare 0.17.4 release

---

CHANGELOG.md
README.md

[Jira Ticket](http://jira.nypl.org/browse/SFR-1760)
- Updates README with C4 Diagram and EPUB to webpub context
-

SFR-1760: Update README C4 Diagram and EPUB to webpub context

---

CHANGELOG.md
package-lock.json
package.json
src/components/About/About.tsx
src/components/About/__snapshots__/About.test.tsx.snap
src/components/AdvancedSearch/AdvancedSearch.tsx
src/components/Collection/Collection.tsx
src/components/Collection/CollectionItem.tsx
src/components/CollectionCard/CollectionCard.tsx
src/components/CollectionItemCard/CollectionItemCard.tsx
src/components/DrbHero/DrbHero.tsx
src/components/EditionCard/EditionCard.tsx
src/components/EditionDetail/Edition.tsx
src/components/EditionDetailDefinitionList/EditionDetailDefinitionList.tsx
src/components/InstanceCard/InstanceCard.tsx
src/components/Landing/Landing.tsx
src/components/License/License.tsx
src/components/License/__snapshots__/License.test.tsx.snap
src/components/Link/Link.tsx
src/components/ResultsList/ResultsList.tsx
src/components/Search/Search.tsx
src/components/SearchForm/SearchForm.tsx
src/components/Work/Work.tsx
src/components/WorkDetailDefinitionList/WorkDetailDefinitionList.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1807)
- Upgrade to NYPL DS 2.1.0
- Convert legacy typography styles to Typo2023 styles 
-

SFR-1807: Reservoir 2.0 Typography changes

---

CHANGELOG.md
src/__tests__/Search.test.tsx
src/components/CollectionCard/CollectionCard.test.tsx
src/components/CollectionCard/CollectionCard.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1822)
- Remove collection image alt text
-

SFR-1822: Remove collection image alt text

---

CHANGELOG.md
package-lock.json
package.json

[Jira Ticket](http://jira.nypl.org/browse/SFR-1836)
- Update version number
-

NOREF prepare 0.17.5 release

---

CHANGELOG.md
playwright/features/pub_yearFilter.feature
playwright/support/mappings.ts
playwright/tests/assertions.spec.ts

[Jira Ticket](http://jira.nypl.org/browse/SFR-1839)
- fixes the automated test failures 
- changes the QA login credentials

DRB PW test failure fix

---

.github/workflows/Playwright.yml
CHANGELOG.md
package-lock.json
package.json

- Update Playwright.yml file to use same versions of cucumber and playwright as package.json (supporting Node 18)
-

NO-REF: update playwright yml

---

CHANGELOG.md
src/__tests__/Search.test.tsx
src/__tests__/componentHelpers/FilterYears.tsx
src/components/AuthorsList/AuthorsList.tsx
src/components/CollectionItemCard/EddLink.tsx
src/components/EditionCard/CardRequiredBadge.tsx
src/components/EditionCard/Ctas.tsx
src/components/EditionCard/DownloadLink.tsx
src/components/EditionCard/EddLink.tsx
src/components/EditionCard/EditionCard.tsx
src/components/EditionCard/FeaturedEditionBadge.tsx
src/components/EditionCard/LanguageDisplayText.tsx
src/components/EditionCard/PhysicalEditionBadge.tsx
src/components/EditionCard/PublisherAndLocation.tsx
src/components/EditionCard/ReadOnlineLink.tsx
src/components/EditionCard/ScanAndDeliverBlurb.tsx
src/components/EditionCard/ViewEditionsLink.tsx
src/components/EditionDetail/Edition.test.tsx
src/components/EditionDetail/Edition.tsx
src/components/FilterYears/FilterYears.tsx
src/components/InstanceCard/InstanceCard.tsx
src/components/InstanceCard/WorldCat.tsx
src/components/ResultsList/ResultsList.tsx
src/components/Search/Search.tsx
src/components/Work/Work.test.tsx
src/components/Work/Work.tsx
src/components/WorkDetailDefinitionList/WorkDetailDefinitionList.tsx
src/util/EditionCardUtils.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1855)
- Add Library Card Required and Featured Edition badges
- Update styles for work/edition pages
-

SFR-1855: Add Library Card Required and Featured Edition badges

---

CHANGELOG.md
src/__tests__/fixtures/EditionCardFixture.ts
src/components/EditionCard/Ctas.tsx
src/components/EditionCard/DownloadLink.tsx
src/components/EditionCard/EditionCard.test.tsx
src/components/EditionCard/EditionCard.tsx
src/components/EditionCard/ReadOnlineLink.tsx
src/components/EditionCard/UpBlurb.tsx
src/types/DataModel.ts
src/util/EditionCardUtils.tsx

[Jira Ticket](http://jira.nypl.org/browse/SFR-1856)
- Implement logic for displaying limited access log in CTAs
- Add blurb for UP items
-

SFR-1856: Add Limited Access CTAs

---

CHANGELOG.md
src/__tests__/componentHelpers/FilterYears.tsx
src/__tests__/componentHelpers/SearchForm.tsx
src/components/CollectionCard/CollectionCard.tsx
src/components/CollectionItemCard/CollectionItemCard.test.tsx
src/components/CollectionItemCard/CollectionItemCard.tsx
src/components/CollectionItemCard/Ctas.tsx
src/components/CollectionItemCard/DownloadLink.tsx
src/components/CollectionItemCard/EddLink.tsx
src/components/CollectionItemCard/ReadOnlineLink.tsx
src/components/EditionCard/Ctas.tsx
src/components/EditionCard/DownloadLink.tsx
src/components/EditionCard/EddLink.tsx
src/components/EditionCard/EditionCard.test.tsx
src/components/EditionCard/ReadOnlineLink.tsx
src/components/EditionDetail/Edition.test.tsx
src/components/InstanceCard/InstanceCard.test.tsx
src/components/InstanceCard/InstanceCard.tsx
src/components/Link/Link.tsx
src/constants/labels.ts

This PR is to the limited-access branch since there would be many conflicting changes if it were to be merged into development due to the refactoring of functions to React components.
[SFR-1847](http://jira.nypl.org/browse/SFR-1847)
[SFR-1848](http://jira.nypl.org/browse/SFR-1848)
[SFR-1849](http://jira.nypl.org/browse/SFR-1849)
- Improves accessibility of CTAs and search bar error message
-

SFR-1847-1849: Accessibility updates for CTAs and search bar error

---

CHANGELOG.md
package-lock.json
package.json

[Jira Ticket](http://jira.nypl.org/browse/SFR-1887)
- Update version number to 0.17.6
-

NOREF prepare 0.17.6 release

---

.github/workflows/build-production.yaml
.github/workflows/build-qa.yml
CHANGELOG.md
package-lock.json
package.json

- Adds APP_ENV (used in NewRelic.tsx) var to build files to embed the correct newrelic browser script
- Updates to latest newrelic package version
-

NO-REF: Add APP_ENV var to build yml files

---

CHANGELOG.md
package-lock.json
package.json

[Jira Ticket](http://jira.nypl.org/browse/SFR-1909)
- Update version number to 0.18.0
-

NOREF prepare 0.18.0 release

---

CHANGELOG.md
src/components/EditionDetail/Edition.tsx
src/components/ResultsList/ResultsList.tsx
src/components/Work/Work.tsx
src/pages/_document.tsx
styles/main.scss

[Jira Ticket](http://jira.nypl.org/browse/SFR-1929)
- Fixes issue where 0 character is shown when there are no authors
- Replace HTML scripts with Next.js Script and add styles to header placeholder to prevent content shift on page load
-

SFR-1929: Fix 0 character issue and misc performance improvements

---

CHANGELOG.md
package-lock.json
package.json

[Jira Ticket](http://jira.nypl.org/browse/SFR-1973)
- Updates version number to 0.18.1
-

SFR-1973: prepare 0.18.1 release

---

CHANGELOG.md
src/components/SearchHeader/SearchHeader.scss

[Jira Ticket](http://jira.nypl.org/browse/SFR-1932)
- Implement a workaround to fix the cut off text in the search bar dropdown.
-

SFR-1932: Fix search bar dropdown issue

---

CHANGELOG.md
src/components/About/About.tsx
src/components/About/__snapshots__/About.test.tsx.snap

[Jira Ticket](http://jira.nypl.org/browse/SFR-1931)
- Replaces invalid work path on the About page with valid path
-

SFR-1931: Update broken link on about page

---

.github/PULL_REQUEST_TEMPLATE
CHANGELOG.md

- Update to new Jira link on PR template
-

NO-REF: Update Jira link on PR template

---

CHANGELOG.md
src/components/ReaderLayout/ReaderLayout.tsx
src/pages/404.tsx

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-1944)
- Updates 404 error page layout
- Shows error message for /read page when there is no available source to be shown in the web reader
-

SFR-1944: Add error handling for invalid read data

---

src/components/ReaderLayout/ReaderLayout.tsx

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2056)
- Only pass the proxyUrl to the web reader when the resource is not internally hosted (limited access books)
-

SFR-2056: Update proxyUrl for limited access books

---

config/appConfig.ts
src/components/About/About.tsx
src/components/About/__snapshots__/About.test.tsx.snap

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-1912)
- QA and Prod have different work ids for the same work, this adds environment value for the respective environment
-

SFR-1912: Add env work links for about page

---

CHANGELOG.md
playwright/support/mappings.ts

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2076)
- updates the press footer web element to address the recurring test failures

SFR-2076/pw_test_fix

---

CHANGELOG.md
package-lock.json
package.json

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2085)
- Prepares for 0.18.2 release

NOREF prepare 0.18.2 release

---

.env.sample
CHANGELOG.md
src/components/Collection/Collection.tsx

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2115)
- Fixes handling an empty collection 
`make test`

SFR-2115: Fix handling empty collection

---

src/pages/_error.tsx

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2168)
- Fixes issue where FeedbackBox reopens with incorrect fields on error pages
-

SFR-2168: Fix FeedbackBox issue

---

CHANGELOG.md
src/__tests__/AdvancedSearch.test.tsx
src/__tests__/fixtures/CollectionFixture.ts
src/components/Collection/Collection.tsx
src/components/CollectionCard/CollectionCard.test.tsx
src/components/Landing/Landing.test.tsx
src/lib/api/CollectionApi.ts
src/lib/api/SearchApi.ts
src/pages/_error.tsx
src/pages/advanced-search/index.tsx
src/pages/collection/[collectionId].tsx
src/pages/edition/[editionId].tsx
src/pages/index.tsx
src/pages/read/[linkId].tsx
src/pages/search/index.tsx
src/pages/work/[workId].tsx
src/types/CollectionQuery.ts
src/types/LanguagesQuery.ts

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2161)
- Update pages to render Error page when there is a server-side error
-

SFR-2161: Render appropriate error page for server-side errors

---

src/pages/_error.tsx

- Updates 400 error message to better reflect error. Product requested that we refrain from using bad requests and server errors in the error message language.
-

NO-REF: Update 400 error message

---

.github/workflows/Playwright.yml
.github/workflows/build-production.yaml
.github/workflows/build-qa.yml
CHANGELOG.md

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-1889)
- Update `actions/checkout`, `actions/setup-node`, `aws-actions/configure-aws-credentials`, and `aws-actions/amazon-ecr-login` Github action versions since Node 16 is deprecated
-

SFR-1889: Update Github action versions

---

CHANGELOG.md
jest.setup.ts
src/__tests__/AdvancedSearch.test.tsx
src/__tests__/Search.test.tsx
src/__tests__/testUtils/render.tsx
src/components/About/About.test.tsx
src/components/Collection/Collection.test.tsx
src/components/CollectionCard/CollectionCard.test.tsx
src/components/CollectionItemCard/CollectionItemCard.test.tsx
src/components/CollectionList/CollectionList.test.tsx
src/components/EditionCard/EditionCard.test.tsx
src/components/EditionDetail/Edition.test.tsx
src/components/EditionDetailDefinitionList/EditionDetailDefinitionList.test.tsx
src/components/Feedback/Feedback.test.tsx
src/components/InstanceCard/InstanceCard.test.tsx
src/components/Landing/Landing.test.tsx
src/components/Layout/Layout.test.tsx
src/components/License/License.test.tsx
src/components/Loading/Loading.test.tsx
src/components/Work/Work.test.tsx
src/components/WorkDetailDefinitionList/WorkDetailDefinitionList.test.tsx
src/util/__tests__/LinkUtils.test.tsx

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-1798)
- Updates unit tests to use custom render function
-

SFR-1798: Update tests to use custom render function

---

CHANGELOG.md
package-lock.json
package.json

- Updates version number to 0.18.3
-

NO-REF prepare 0.18.3 release

---

CHANGELOG.md
package-lock.json
package.json

- Updates version number to 0.18.4
-

NO-REF prepare 0.18.4 for release

---

.github/workflows/Playwright.yml
CHANGELOG.md
cucumber.json
package-lock.json
package.json
src/pages/_document.tsx

SFR-2279: Release 0.18.5 to production

---

CHANGELOG.md
package-lock.json
package.json

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2290)
- Prepares for the 0.18.6 release

NO-REF: prepare 0.18.6 release

---

CHANGELOG.md
package-lock.json
package.json

NO-REF: Prepare 0.18.7 release

---

CHANGELOG.md
package-lock.json
package.json
src/components/Collection/Collection.tsx
src/components/EditionDetail/Edition.tsx
src/components/Landing/Landing.tsx
src/components/Search/Search.tsx
src/components/SurveyBanner/SurveyBanner.tsx
src/components/Work/Work.tsx
src/pages/_document.tsx

- Add survey banner to Landing, Collection, Edition, Work, and Search pages

Release 0.18.8 to production

---

CHANGELOG.md
src/components/SurveyBanner/SurveyBanner.tsx

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2367)
[Figma](https://www.figma.com/design/O7xYTHlHFQdPVsK5PycbDC/DRB---Miscellaneous?node-id=3266-1154&t=QdSRzD7eRqAWQplJ-4)
- Updates survey banner styles
Updated landing page:
Updated mobile:
-

SFR-2367: Update survey banner to be more visible

---

CHANGELOG.md
package-lock.json
package.json

NO-REF prepare 0.18.9 release

---

.github/workflows/build-production.yaml
.github/workflows/build-qa.yml
CHANGELOG.md

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2406)
- Deploys to the new terraform stacks in QA and prod only

SFR-2406: Deploy only to the new Terraform stacks

---

CHANGELOG.md
package-lock.json
package.json

NO-REF prepare 0.18.11 for release

---

CHANGELOG.md
src/pages/_document.tsx

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2448)
- Update OptinMonster script
-

SFR-2448: Update optinmonster script

---

src/pages/_app.tsx
src/pages/_document.tsx

- The script was not showing on QA. The default value for the strategy prop was not being filled in _document.ts file. Moved to the _app.ts file as per [this doc](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts)
-

NO-REF move optinmonster script to _app

---

CHANGELOG.md
package-lock.json
package.json

NO-REF prepare 0.18.12 for release

---

.github/workflows/Playwright.yml
.github/workflows/build-production.yaml
.github/workflows/build-qa.yml
.github/workflows/full-ci-cd.yml
CHANGELOG.md

[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2404)
- Implement full CI/CD workflow
- Change auto tag step to auto bump and tag for prod release
-

SFR-2404: Implement full ci/cd workflow

---

.github/workflows/Playwright.yml
.github/workflows/ci.yml
.github/workflows/rollback.yml
CHANGELOG.md

- Updates the Playwright.yml step for setting environment and calling the workflow from ci.yml 
-

NO-REF: Fix Playwright env setting step
