NYPL/sfr-bookfinder-front-end

src/app/components/Application/Application.jsx, src/app/components/List/EBookList.jsx, src/app/components/SearchContainer/SearchContainer.jsx, src/app/components/SearchResults/ResultsList.jsx, src/app/components/SearchResults/ResultsMetadata.jsx, src/app/components/SearchResults/ResultsRow.jsx, src/app/components/SearchResults/SearchResults.jsx, src/app/components/WorkDetail/DefinitionList.jsx, src/app/components/WorkDetail/WorkDetail.jsx, test/fixtures/results-list.json, test/unit/DefinitionList.test.js, test/unit/ResultsList.test.js, test/unit/ResultsRow.test.js
Adds list component for ebook links which need to show "Download" forexternally hosted ebooks and "Read Online" for locally hosted ebooks.
Attempts to fulfill requirements for [SFR-92](https://jira.nypl.org/browse/SFR-92) to provide a link to open an ebook in our local eReader if we host the ebook or a download link if the ebook is hosted externally.
Tests are included, but they are fairly brittle. Need to continue to work on shoring these up.
=> Rewrite ebook links (local vs. external)

src/app/actions/SearchActions.js, src/app/components/SearchForm/SearchForm.jsx, src/app/components/WorkDetail/WorkDetail.jsx, src/app/search/query.js, src/app/stores/Reducers.js, test/fixtures/work-detail.json, test/unit/DefinitionList.test.js, test/unit/Query.test.js, test/unit/ResultsMetadata.test.js, test/unit/SearchActions.test.js
Adds `field` to the location when searching via the client. The server should also respond to the `field` query parameter. Query objects are now built using a utility function which I'm hoping I can expand to adding filter, aggregations, sort, page and per_page elements. Some tests have been added just for testing the field queries built to send along to ES.
In the query builder, phrases are split into words, encoding moved here, and each word is added as separate field queries in an array which acts as an AND for all words so each must be present in the field. The query builder removes some punctuation including commas to split words properly which helps for author searches. This PR should satisfy all basic field level querying which need to have terms AND'd together.
=> Title (field) search

src/app/search/query.js, test/unit/Query.test.js
Fixes issues with sending the a user input query properly to the search API. Uses an escape character strategy rather than removing ES escape characters.
=> Small fix to query parsing

appConfig.js, package.json, src/app/components/SearchForm/SearchForm.jsx, src/app/components/WorkDetail/DefinitionList.jsx, src/app/components/WorkDetail/WorkDetail.jsx, src/app/constants/fields.js, src/app/search/query.js, src/client/styles/components/Search.scss, src/client/styles/main.scss, test/unit/Query.test.js, test/unit/SearchForm.test.js
* adds subject search option to form
* consolidates option value rendering on SearchForm 
* adds the change-case npm package for capitalizing labels for search form options and other potential uses in the project. If there's a better one, just let me know.
* adds onClick handler for author and subject links on detail pages to the DefinitionList component
** passed dispatch and context from WorkDetail component for onClick handler
=> Add subject search

src/app/components/WorkDetail/DefinitionList.jsx
Adds quotes around queries that "browse" the index via subjects and authors. The subject links in particular need to be quoted, or any other multi-word search terms, to ensure an exact match.
Author links may change to use their identifiers instead, but the change here to search the exact name via quotes should provide the expected result.
=> Add phrase searching for browse links

package.json, src/app/actions/SearchActions.js, src/app/components/Breadcrumbs/Breadcrumbs.jsx, src/app/components/SearchContainer/SearchContainer.jsx, src/app/components/SearchForm/SearchForm.jsx, src/app/components/WorkDetail/DefinitionList.jsx, src/app/components/WorkDetail/WorkDetail.jsx, src/app/search/query.js, src/app/stores/InitialState.js, src/app/stores/Reducers.js, src/app/stores/ReduxStore.js, src/app/stores/configureStore.js, src/client/App.jsx, src/client/styles/main.scss, src/server/ApiRoutes/Search.js, test/unit/Breadcrumbs.test.js, test/unit/Query.test.js, test/unit/SearchContainer.test.js
The breadcrumbs component adds links in a trail from the home page of ResearchNow to the details view. One should be able to navigate back to either the search results one just came from if on a detail page, or back to the home page with a fresh start. Breadcrumbs should work the same whether or not the search was initiated from the form, a browse link, or a request via the address bar, e.g. /search?q=journey&field=title. Includes tests and some inline documentation.
=> Add Breadcrumbs

src/app/components/List/EBookList.jsx
This implements the boolean/flag link type checking on the front end that has been implemented on the back end. This is a necessary upgrade to prevent the React app from displaying "Download" for all links as the `rel_type` field that previously controlled this has been removed.
This does not implement further UI features such as the external link icon, which should fall to SFR-413.
=> SFR-412 Improve link designations

src/app/components/Svgs/BookSvg.jsx, src/app/components/Svgs/EmptySearchSvg.jsx
After talking about it with @nachocs, I didn't add them as editable strings you can manipulate in the `<BookSvg />` element as they only refer to that particular image (seemed like overkill).
=> SFR-474: Adds title and aria-labelledby elements for decorative book svgs

src/app/components/SearchContainer/SearchContainer.jsx
Removes it from the search container to match the pattern of the search results page.
=> SFR-466: Removes duplicate search role

src/app/components/Form/TextInput.jsx
Removes it from `TextInput.jsx` based on [Willa's comment on Jira](https://jira.nypl.org/browse/SFR-464?focusedCommentId=33488&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-33488).
=> SFR-464: Removes additional aria-labelledby attribute on text inputs

src/app/components/List/EditionsList.jsx
Adapt to new JSON response with edition_count property and limited intances. 
Also valid as it is now.
=> Adapt to new JSON response with edition_count

src/server/ApiRoutes/Search.js
On the server side, there is a state when the url have an invalid query (like start year after end year), that triggers a server error internally and the app blocks itself in the server side.
With this change, it triggers a server error (that is ok as it's invalid query), but the app can keep on working.
Not really sure if it's related to the ticket, as I couldn't reproduce it, but anyway an improvement. Probably any error should be logged in the future.
=> SFR-575 Advanced Search - refreshing page triggers Internal Server Error

src/app/components/List/EBookList.jsx, src/app/libraries/react-dropdown-aria.jsx
Introduced a bug in the last commit.  This approach, where the label is decoupled from the key, is better.
=> IDs shouldn't show up in visible labels

appConfig.js, server.js
This adds the new ResearchNow-specific Google Analytics code, replacing the default NYPL code that is brought in through the `dgx-react-ga` component. That library is still used to load the code/provide other functionality. Two options for different ga codes are provided: `production` and `development` but one code is used for both for now. In the future it will be possible to specify different properties for different versions of the app
=> SFR-594 Add new analytics property

src/client/App.jsx
As a single-page application ResearchNow requires a little additional configuration to track page views, and through that, search events. This can be done by hooking into the history object and listening to changes to the history, which can fire the ga tracker. With these events in ga the site search features should work automatically.
This can't be tested locally but I `console.log`'d the output of `location.pathname` on page load and it does fire properly on page changes/loads with a path that GA should understand
=> SFR-595 Add ga tracker for pages

src/client/App.jsx
This adds the URL parameters from `location.search` to the ga pageview tracker, which is necessary to track site searches. The URL parameters object is called `search` but seems to include all parameters, including for work pages. Unecessary parameters will be filtered out in ga, so this should not present a problem.
=> SFR-595 Add search params to analytics tracker

src/app/components/SearchForm/SearchForm.jsx, src/app/components/SearchResults/AdvancedSearchResults.jsx, src/app/stores/InitialState.js, test/unit/AdvancedSearch.test.js, test/unit/SearchContainer.test.js, test/unit/SearchForm.test.js
Updated tests as well
Not really sold on this approach, (the hardcoding of the first entry in `queries`) but it's working ok.  Happy to take another look at it now, or defer to when we have new designs!
=> SFR-668 removed 'query' and 'keyword' parameters in favor of 'queries'

src/client/styles/main.scss
In RN the breadcrumb wasn't showing an underline on hover, because this was over-riding it.
=> SFR-616 Removed hover text-decoration

src/views/index.ejs
Sets that min-height to `208px` instead of `230px`. This means we deviate from what the [React Header](https://github.com/NYPL/dgx-header-component) recommends, so I left a comment with a reference to the ticket until that documentation updates.
=> [771] Updates the min-height of the header embed

src/app/components/SearchForm/SearchForm.jsx, src/app/components/WorkDetail/DefinitionList.jsx
This fixes several issues around the handling of queries. The initial ticket was to investigate `500` errors stemming from making subject queries from the work detail pages. That seems to have been fixed by a different change, however investigating it revealed that non-keyword searches were not being executed properly and that the subject searches from the detail pages were not properly displaying the query "pills".
Both issues were due to their respective components using the old-style simple search query structure. Updating both of these to the new advanced search structure has fixed both issues.
The one point that could use further review is coming from the detail page I had to encode the query array as a string to get the app to parse it correctly, otherwise it rendered it as a …
=> SFR-761 fix subject query handling

webpack.config.babel.js
To make the Airtable key (loaded as an env var) available to the react app it must be loaded through the webpack config. This is done separately in the production and development environments and the previous commit ommitted the production code, meaning the feedback form cannot be submitted from deployed versions of the app.
=> SFR-442 Add Airtable key to production

src/app/components/Card/EditionCard.jsx, test/unit/EditionCard.test.js
The method that constructs author searches form detail pages and search results was passing `name` as the query `field`. This should be `author` the method was returng the same field for both the `query` lookup and the `field` which works for VIAF and LCNAF queries but not for author name searches.
I've updated this to return a tuple, which is then accessed in the calling method. This fixes the issue and should "future-proof" this a bit in case we want to add future searches which may require different field and query names.
Also added are a few tests on the method to ensure that it returns the expected value.
=> SFR-593 Fix author name search

src/app/components/LandingPage/LandingPage.jsx, src/app/components/SearchForm/SearchForm.jsx, src/app/components/SearchForm/SearchHeader.jsx, src/app/components/SearchForm/WithSearch.jsx, src/app/components/SearchResults/SearchResultsPage.jsx, src/app/components/WorkDetail/WorkDetail.jsx, test/unit/LandingPage.test.js, test/unit/SearchResultsPage.test.js, test/unit/WorkDetail.test.js
For info on what HOCs are => https://reactjs.org/docs/higher-order-components.html
This is really quite a textbook case to use HOCs, all the lifecycle methods for the two components are the same, but it needs to render different things.  In the past, this could have been done via
```
render() {
return shouldBeSearchPromo ? <SearchPromo /> : <SearchHeader /> 
}
```
(and we did something that was conceptually similar)
but this is way saner
The thing I didn't do was abstract out the unit tests - since they're all on lifecycle and event stuff, it would be a lot of mocking and simulating that I haven't yet figured out how to do without going slightly mad
=> SFR-811 Consolidated SearchForm and SearchHeader

src/app/components/Card/EditionCard.jsx, src/app/components/SearchResults/ResultsList.jsx, src/app/components/WorkDetail/WorkDetail.jsx, src/client/styles/components/RequestDigitization.scss
[Jira Ticket](http://jira.nypl.org/browse/SFR-89)
- Adds an underline class to the request digitization link
- This class is usually added by a default User Agent stylesheet, but it isn't getting applied here because the `<a>` has no `href`
- This style will be removed when we figure out a way to display the "Request Digitization" not-quite-button-because-it-looks-like-a-link. 
-
=> SFR-89 Added underline to request digitization link

src/client/styles/main.scss
[Jira Ticket](http://jira.nypl.org/browse/SFR-866)
- Fixes vertical alignment for type on homepage within header area
- Extends the background color on the header to the sides of the page
Current:
After hotfix:
Please note this should be ripped out after a release for the new hero gets cut for the DS.
=> [SFR-866] Landing Header Hotfix

src/app/components/AdvancedSearch/AdvancedSearch.jsx, src/app/components/Card/EditionCard.jsx, src/app/components/SearchForm/SearchForm.jsx, src/app/components/SearchForm/SearchHeader.jsx, src/app/components/SearchForm/WithSearch.jsx, src/app/components/SearchResults/SearchResultsPage.jsx, src/app/constants/fields.js, src/app/stores/InitialState.js, test/unit/AdvancedSearch.test.js, test/unit/WithSearch.test.js
[Jira Ticket](http://jira.nypl.org/browse/SFR-843)
- Query and ShowQuery were inferring values off of each other.  
- This PR separates them so that they are always set differently.  This allows us to handle queries that are used in search (eg: viaf) that are different from what is shown to the user,  (eg: if searching by viaf, should override author search, but author search should be used when no viaf is available) 
-
=> SFR-843 Separated out Query and ShowQuery 

appConfig.js, package.json, src/app/components/Card/EditionCard.jsx, src/app/components/Viewer/EBookViewer.jsx, src/app/util/Util.jsx, test/unit/Util.test.js, webpack.config.babel.js
HOTFIX - No JIRA ticket
The `formatUrl` shim was put in to force URLs to use a certain protocol for environmental reasons (generally being forced to https). Due to updates in the environments this is no longer necessary.
The method is still in place but now simply adds a protocol to any URL that is missing one (this is necessary, for example, with covers). This should allow for certain components, such as the reader app, to work as intended in all environments.
This also adds a new environment: `local`. This is similar to `development` but has some specific settings to allow for easier local development. It can be started by using `npm run local-start` and requires that a local instance of the webpub-reader app be running at `localhost:4444`
- Run a local instance of the app with `npm run …
=> HOTFIX Remove HTTP protocol coercion

CHANGELOG.md, package.json, src/app/components/Card/EditionCard.jsx, test/unit/EditionCard.test.js, test/unit/ResultsList.test.js
[Jira Ticket](http://jira.nypl.org/browse/SFR-885)
- Adds `onClick` events to the "Read Online" and "Download" buttons in edition cards that trigger GA tracking events that record which button was clicked, the source of the edition being accessed and the title of the work
-  Verify that the onClick triggers are present in all cases
- (Optional) trigger an event and verify that it appears in the Google Analytics reports
=> SFR-885 Add GA tracking events for Read Online and Download buttons

CHANGELOG.md, README.md, package-lock.json, package.json, src/app/components/Application/Application.jsx
[Jira Ticket](http://jira.nypl.org/browse/RENO-1463)
The previous version of dgx-react-footer used relative urls for the NYPL footer links. For apps such as this one, which live on a different domain, those links don't work correctly.
The new version of dgx-react-footer adds a new prop called urlType which can optionally be passed into the Footer component to maintain absolute urls for the footer links.
This approach is similar to how the dgx-header-component handles links.
- Updates dgx-react-footer to v0.5.7
- Adds the new urlType prop to the Footer component in `Application.jsx`
-  The NYPL links in the footer section should now all be absolute urls and open as expected.
I did not bump the version for the app, as I assumed this update will be packaged with other work that is in …
=> RENO-1463 Account for absolute links in footer

.github/workflows/destroy-branch-qa.yaml, CHANGELOG.md
The action that tears down the temporary testing environment was missing an environment variable that provided the branch name. This resulted in the process erroring. Adding the variable resolves the problem.
No testing required. An identical fix was necessary on the back-end repo and resolved the issue.
=> Hotfix add variable to destroy action

.github/workflows/build-branch-qa.yaml, CHANGELOG.md, task-definition.json
The front-end application is calling the local API instance, but on the incorrect port, this attempts to fix the issue by statically specifying that port.
Verify that the app is able to query the API
=> HOTFIX Specify API port

.github/workflows/build-branch-qa.yaml
This commit includes one fix and one improvement to the QA deployment process.
The fix is to correct a regression that was causing the `latest` tag for the application container to be deployed. The updated `task-definition` was not being passed in the correct step
The improvement is to tag images with the branch name instead of the git hash, this makes them more identifiable.
=> HOTFIX Update branch tags

CHANGELOG.md, src/components/Layout/Layout.tsx
[Jira Ticket](http://jira.nypl.org/browse/SFR-1073)
This simply sets the favicon link for the site in the `head` element. It does so alongside the `title` element which means that this should be easy to locate/update in the future if necessary.
The favicon URL is loaded from the `appConfig` file and should be changed there if the icon itself changes.
The testing environment should be reviewed to confirm that the icon appears on all pages
=> Sfr 1073 add favicon

src/__tests__/Search.test.tsx, src/components/SearchHeader/SearchHeader.scss, src/components/SearchHeader/SearchHeader.tsx, src/components/Work/Work.test.tsx
[Jira Ticket](http://jira.nypl.org/browse/SFR-1071)
- Removes h1 duplication by removing it from the search header.  
- Restyles the search header to look like a header
- Changes the search header to be a link 
-
=> Removed extra <h1> and made the header a link

.github/workflows/build-qa.yml
A recent change to how environment variables are handled required an update to how containers are built. As part of this process a YAML line was copied between files for GHA that contains a reference to an undefined variable. This resovles the issue by using a present value for the tag
When merged ensure that the deployment works properly
=> HOTFIX Container build tag

.github/workflows/build-production.yaml
- Adds a production build action that is triggered against merges to the production branch (automated production deployments)
-  This can't be tested and should be verified to work properly before the formal launch on 6/9 (aka merge this along with a functional change into production and be sure that the functional change deploys properly)
=> NOREF Add production build step to GHA

task-definition.json
This is necessary due to an update in the API client
=> NOREF Add Redis Host for test environment

.github/workflows/rspec-integration-tests.yml
[Jira Ticket](http://jira.nypl.org/browse/SFR-1193)
- Adds a GHA to run the rspec integration test suite against the application currently deployed on QA
-  Verify that the GHA runs and that the integration test pass (and have run against the proper application)
This executes the integration test suite when PRs are opened against production. This should protect against obvious regressions and provides a way of running automated tests in a way that picks up new tests without dev/QA intervention. This PR runs these tests against development to verify that the action works as intended but will be updated to run only against production before being merged in.
=> SFR-1193 Run rspec tests

src/components/ReaderLayout/ReaderLayout.tsx, src/lib/api/SearchApi.ts, src/pages/read/[linkId].tsx, task-definition.json
[Jira Ticket](http://jira.nypl.org/browse/SFR-1235)
The `proxyUrl` is provided to the new web reader component to enable the display of PDFs. This relies on server-side only environment variables to construct this value (specifically `API_URL`) and was unable to retrieve these values.
This updates the component by constructing the value on the server-side and passing it in as a new prop. A simple method constructs the string and should make it available in all cases.
The test deployment here should successfully be able to load PDF files in the web reader via the local proxy
=> SFR-1235 Proxy URL Fix

package-lock.json, package.json
No Jira Ticket
- Updates @nypl/web-reader package so that PDF rendering performance enhancements in scrolling mode can be tested by QA
-  Load a large single-resource PDF in Firefox, Chrome, or Safari. The resource should render in scrolling mode without issue. Browser should not crash.
=> Upgrades web-reader to 0.2.5

CHANGELOG.md, src/util/LinkUtils.ts
[Jira Ticket](http://jira.nypl.org/browse/SFR-1505)
- Changes the check for "search" to the endpoint "/search" to prevent links without the endpoint from being recognized as a search results link for prod, i.e. digital-re**search**-books-beta.nypl.org
-
=> SFR-1505: Fix back to search results bug

CHANGELOG.md, src/components/ReaderLayout/ReaderLayout.tsx, src/pages/_app.tsx, src/pages/_document.tsx
[Jira Ticket](http://jira.nypl.org/browse/SFR-1711)
- Hides the header/footer components if the web reader is displayed on /read endpoints.
- Removes type="module" from the Header/Footer scripts following updates from nypl-header-app.
-
=> SFR-1711: Remove header/footer from web reader page 

CHANGELOG.md, playwright/features/advSearch.feature, playwright/support/mappings.ts, playwright/tests/assertions.spec.ts
[Jira Ticket](http://jira.nypl.org/browse/SFR-1743)
This PR is a playwright tests for DRB advance search language filters. It verifies the followings
- when language checkbox is checked, after search we verify the language checkbox is checked on results page
- correct language titles are showing up
- read online button is being displayed
=> SFR-1743/advance-search-language-filter

CHANGELOG.md, src/constants/analytics.ts, src/pages/_app.tsx, src/pages/_document.tsx, src/util/SearchQueryUtils.ts
[Jira Ticket](http://jira.nypl.org/browse/SFR-1762)
- Update Adobe Analytics page names to fit [best practices](https://blastwiki.atlassian.net/wiki/spaces/NYPL/pages/7898713056097665227/Page+Name+Taxonomy+-+URLs+and+EXAMPLE+PAGE+NAMES)
- Move Adobe Analytics script to _document.tsx file 
-
=> SFR-1762: Update Adobe Analytic page names

.github/workflows/build-production.yaml, .github/workflows/build-qa.yml, CHANGELOG.md
[Jira Ticket](http://jira.nypl.org/browse/SFR-1779)
- Update the production yaml file to have a unique ECR image tag.
When our ECS cluster automatically restarts, the :latest docker build is pulled, which could be a QA build. This was never an issue since we had not used hard-coded build arguments prior to the New Relic instrumentation.
=> SFR-1779: Fix incorrect prod args

CHANGELOG.md, src/__tests__/AdvancedSearch.test.tsx, src/__tests__/Search.test.tsx, src/__tests__/componentHelpers/FilterYears.tsx, src/__tests__/componentHelpers/SearchForm.tsx, src/components/Collection/Collection.test.tsx, src/components/EditionDetail/Edition.test.tsx, src/components/Feedback/Feedback.test.tsx, src/components/Work/Work.test.tsx
[Jira Ticket](http://jira.nypl.org/browse/SFR-1780)
- Replace fireEvent with userEvent
-
=> SFR-1780: Replace fireEvent with userEvent

CHANGELOG.md, src/__tests__/AdvancedSearch.test.tsx, src/constants/editioncard.ts, src/constants/labels.ts, src/pages/collection/[collectionId].tsx, src/pages/edition/[editionId].tsx, src/pages/work/[workId].tsx
[Jira Ticket](http://jira.nypl.org/browse/SFR-1799)
- Update Collection, Edition, and Work page titles for accessibility
-
=> SFR-1799/1800: Update page titles for accessibility

.github/CODEOWNERS, CHANGELOG.md
- Adds Jackie and Sam as codeowners for the entire repo. This means Jackie or Sam will need to approve a PR before merging to `development`.
=> NO-REF: Add Jackie and Sam as codeowners

CHANGELOG.md, playwright/features/edd.feature
[Jira Ticket](http://jira.nypl.org/browse/SFR-1869)
- Adds assertion step to `edd.feature` that confirms a button exists before attempting to click it
-  Run Playwright tests and all tests pass
=> SFR-1869: Add assertion step to Playwright test

CHANGELOG.md, src/components/EditionCard/DownloadLink.tsx, src/components/EditionCard/ScanAndDeliverBlurb.tsx, src/components/EditionCard/UpBlurb.tsx, src/lib/api/SearchApi.ts, src/types/FulfillQuery.ts, src/util/EditionCardUtils.tsx
Note: Apoorva agrees that Modals should not be used in the long run for error handling and will speak to DS to explore different types of notifications.
[Jira Ticket](http://jira.nypl.org/browse/SFR-1894)
- Add modal for error handling of /fulfill
- Update getPreviewItem to prioritize the UP items
-
=> SFR-1894: Add error modal for /fulfill errors

CHANGELOG.md, package-lock.json
- Fixes issue where PDF does not load on web reader due to pdfjs-dist version mismatch. Updates the version in package-lock.json
-
=> Hotfix: Fix failed to load pdf error

CHANGELOG.md, src/util/EditionCardUtils.tsx
- Removes featured edition logic from the frontend and uses the first edition item since the backend added sorting for the items.
-
=> NOREF: Remove featured edition logic

.github/CODEOWNERS, CHANGELOG.md
- Adds Kristo, Jiayong, and Olivia as codeowners
-
=> NO-REF: Add Kristo, Jiayong, and Olivia as codeowners

src/components/EditionDetail/Edition.tsx, src/util/EditionCardUtils.tsx
- Fixes errors for edition and work pages related to updates on the backend where editions are no longer passing an items object 
-
=> NO-REF: Fix error for edition and work pages

CHANGELOG.md, src/components/EditionDetailDefinitionList/EditionDetailDefinitionList.tsx
[Jira Ticket](http://jira.nypl.org/browse/SFR-1898)
- Combine publisher lists to be a single list for better accessibility
-
=> SFR-1898: Combine publisher lists on edition page

CHANGELOG.md, playwright/support/mappings.ts
[Jira Ticket](http://jira.nypl.org/browse/SFR-1917)
- Fixed Cucumber/Playwright failing tests
- Run Playwright tests and all tests pass
=> SFR-1917: Fix failing Playwright tests

.github/workflows/build-production.yaml, CHANGELOG.md
[Jira Ticket](http://jira.nypl.org/browse/SFR-1568)
- Updates Github Action for release from create-release to action-gh-release
- Fixes action-autotag error by declaring GITHUB_TOKEN as an env var
-
=> SFR-1568: Update release github action

.github/workflows/build-production.yaml, .github/workflows/build-qa.yml, CHANGELOG.md, Dockerfile
[Jira Ticket](http://jira.nypl.org/browse/SFR-1905)
- Previously had added the env var for APP_ENV to the yml build files, but did not include it as a build-arg for the docker build command.
-
=> SFR-1905: Add build arg to yml files

CHANGELOG.md, README.md
[Jira Ticket](http://jira.nypl.org/browse/SFR-1940)
- Update README with production release info
-
=> SFR-1940: Update readme with prod release info

CHANGELOG.md, playwright/features/licensePage.feature, playwright/support/mappings.ts
[Jira Ticket][(http://jira.nypl.org/browse/SFR-XXX](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2008))
- validates the header and sub-header body of whole License Page of DRB
=> SFR-2008/Automate_License_Page

CHANGELOG.md, playwright/features/headerLinks.feature, playwright/support/mappings.ts
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2033)
- verifies the external NYPL app links nested inside DRB app
- verifies when clicked on the links user is directed to the correct landing pages.
=> SFR-2033/verify-nypl-header-links

CHANGELOG.md, package-lock.json, package.json, src/components/EditionCard/EditionCard.test.tsx, src/components/EditionCard/ReadOnlineLink.tsx, src/components/InstanceCard/InstanceCard.test.tsx, src/components/InstanceCard/InstanceCard.tsx, src/components/ReaderLayout/ReaderLayout.tsx, src/types/DataModel.ts, src/util/EditionCardUtils.tsx
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-1969)
- Adds "Read Online" functionality for University Press items by passing custom fetcher to the web reader
-
=> SFR-1969: Add "Read Online" functionality for UP items

CHANGELOG.md, config/appConfig.ts
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2032)
- Updates the local API url to http://localhost:5050
- 5050 is based on the the docker-compose.yml [file](https://github.com/NYPL/drb-etl-pipeline/blob/main/docker-compose.yml#L59) in the ETL pipeline
- No testing required. This is just an app config change.
=> SFR-2032: Update local API url

.github/workflows/build-production.yaml, CHANGELOG.md
- Pins the `butlerlogic/action-autotag` version to 1.1.2 since the stable version is using an unsupported version of Node.js
-
=> NO-REF: Pin butlerlogic/action-autotag version

CHANGELOG.md, src/components/CollectionList/CollectionList.tsx
- Checks if the collection groups is defined before mapping the data to display the list of collections
=> NO-REF: Hot fix - check if collection groups is defined

Dockerfile
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2196)
- Fixes issue where `docker run` does not find newrelic.js file. Copies the newrelic.js file for running the Next.js standalone server.
-
=> SFR-2196: Fix issue with New Relic and standalone Next.js server

Dockerfile, next.config.js
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2196)
- Expose New Relic env vars for runtime and update next.config.js to externalize thrid party libraries as per the official [newrelic example](https://github.com/newrelic/newrelic-node-examples/blob/main/nextjs/nextjs-app-router/next.config.js)
-
=> SFR-2196: Expose New Relic env vars for runtime

CHANGELOG.md, playwright/features/copyrightPage.feature, playwright/features/drbFooters.feature, playwright/features/headerLinks.feature, playwright/support/mappings.ts
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2257)
- updates the license page to copywright page for PW tests
- updates the name licensePage.feature to copyrightPage.feature
- updates the mapping related to license page headers and subheaders
=> SFR: 2257 - fix pw tests for license page changes

.github/workflows/Playwright.yml, CHANGELOG.md, cucumber.json, package-lock.json, package.json
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2238)
- updates the Playwright.yml file to trigger GHA test on every pull request on localhost server
=> SFR 2238/run gha on local

CHANGELOG.md, package-lock.json, package.json
[SFR-2279](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2279)
- Upgrades version to 0.18.5 to prepare for the release
[SFR-2279]: https://newyorkpubliclibrary.atlassian.net/browse/SFR-2279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NOREF prepare 0.18.5 release

CHANGELOG.md, src/lib/api/FeedbackApi.ts
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2263)
- Adds submit feedback error handling from Jackie's previous PR
- Adds date and environment fields so we can filter out data
-  `npm run dev -> submitted feedback`
=> SFR-2263: Add submit feedback error handling and audit data

CHANGELOG.md, src/pages/_document.tsx
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-XXX)
- Fixes header when banner is up
-  npm run dev
=> NO-REF: Fix header when banner is up

CHANGELOG.md, package-lock.json, package.json, src/pages/_document.tsx
[NO-REF: Fix header when banner is up](https://github.com/NYPL/sfr-bookfinder-front-end/commit/1ac22ee5431512f1365b8a97210138dff4099dc7)
=> Release 0.18.7 to production

CHANGELOG.md, src/components/Collection/Collection.tsx, src/components/EditionDetail/Edition.tsx, src/components/Landing/Landing.tsx, src/components/Search/Search.tsx, src/components/SurveyBanner/SurveyBanner.tsx, src/components/Work/Work.tsx
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2300)
[Figma](https://www.figma.com/design/O7xYTHlHFQdPVsK5PycbDC/DRB---Miscellaneous?node-id=3219-4212&node-type=frame&t=876LCc3x5biRxCCC-0)
- Add survey banner to Landing, Collection, Edition, Work, and Search pages
-
=> SFR-2300: Add survey banner to DRB

CHANGELOG.md, package-lock.json, package.json
=> NO-REF prepare 0.18.8 for release

.github/workflows/Playwright.yml, CHANGELOG.md, playwright/features/eReader-settings.feature, playwright/features/edd.feature
- Enables playwright tests on PR
=> SFR-2317: Enabling playwright tests on PR

.github/CODEOWNERS, CHANGELOG.md
- Remove Kristo, Jiayong, and Olivia and add Kyle as codeowner
-
=> NO-REF: Update codeowners

.github/workflows/build-production.yaml, CHANGELOG.md
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/jira/software/c/projects/SFR/boards/130?assignee=712020%3A4ff7b903-7103-4b3d-ada8-a9e78f8b4aff)
- Deploys frontend changes to the TF production ECS cluster
=> SFR-2396: Deploy to new terraform ECS cluster

CHANGELOG.md, package-lock.json, package.json
- Updates version to 0.18.10
-
=> NO-REF prepare 0.18.10 for release

CHANGELOG.md, src/pages/_document.tsx
[Jira Ticket](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2449)
- Add scripts for Google Tag Manager
-
=> SFR-2449: Add GTM scripts
